### ISSUE TITLE
Confuse

### ISSUE THREAD

**Issue by yejy53** [Skyy93/Sample4Geo#11]
Thank you for your excellent work, but I found that when I used the polar coordinate transformed image to retrieve, it looked worse than directly using the original sat view to retrieve. This is not in line with intuition, because polar coordinate transformation seems to be beneficial in other networks. !

**Comment by Skyy93** [comment]
Thank you for your interest. We have explicitly not trained our approach with the Polar Transformation. Therefore, the results are worse when using it but evaluated with our weights. We explicitly decided against it because the polar transformation significantly slows down the training and also distorts the satellite image.
