### ISSUE TITLE
Missing implementation of DSS in University1562

### ISSUE THREAD

**Issue by Yux1angJi** [Skyy93/Sample4Geo#19]
Thanks for your interesting work.
However, I can not find the implementation of Dynamic similarity sampling in the code, where there is only one custom sampler to prevent the occurrence of multiple images from the same class. 
Does it mean that there is no special sampling method for University1562?

**Comment by Skyy93** [comment]
We tried the sampling for U1652 but it did not improve the score, therefore we did not implement it for the public release.

**Comment by AthanasiosKwn** [comment]
Hello! @Skyy93 
When you say that DSS did not provide better results in University1652 according to the baseline that is now found in the repository for the U1652 case, do you mean that it did not improve the baseline's score - aka produced same results- or that it produced worse results, and if so, how worse, what was the difference in metric values?

**Comment by Skyy93** [comment]
Hi @AthanasiosKwn 
thank you for the interest in our work. It produced slightly worse results but it was minor, in the 1-2% area difference.

**Comment by AthanasiosKwn** [comment]
@Skyy93  Thanks for the quick answer! Any comments on why hard negatives substantially improved the results on the other three datasets, whereas on University1652 the results got worse?

**Comment by Skyy93** [comment]
@AthanasiosKwn Some of the Universities used in the dataset are used multiple times with buildings very near to each other. So there can be images where two buildings are visible and this can result in confusion for the model, because both buildings are visible but only one is the correct one, but which? 

Sampling explicitly for hard negatives results in this images which do not have a clear boundry. In a subsequent publication we discovered that predicting the orientation helps for better performance as then the model learns how the UAV Images are ordered around the building.

This is a general problem in hard negative sampling, how to deteremine false negatives or images that might be negative but are so near to a positive that its hard to distinguish. 

In the other three datasets the locations are not really overlapping. In the VIGOR dataset you have the semi-positive ones and when you try to include them the performance goes down as well. If you are interested in these topics, we are currently organizing a workshop at the ACM MM in fall (https://www.zdzheng.xyz/ACMMM2025Workshop-UAV/) and I am also very interested in this topic, so feel free to ask further!

**Comment by AthanasiosKwn** [comment]
@Skyy93 I knew that images were taken from multiple buildings from each university, but it never occured to me that there could be some images that contain two or more buildings of the dataset, in other words that a building can be spotted in images tagged with different building id's.

So, even though the custom batch sampler is used to ensure that each batch contains no more than one image pair (uav-satellite pair) from the same building, meaning that the negative pairs for each anchor point are indeed negative, because this sampling is based only on building id's there is a slight probability that this will not happen due to the above observation, introducing label noise to the contrastive learning process? 

And this phenomenon is amplified when DSS is used because there is a high risk that the hard negatives retrieved are images that contain the anchor point somewhere in the background meaning that these are not true negatives? Please correct me if I am wrong.

If that is the case, then it is interesting to see if DSS coupled with some robust to label noise add-on methodology can also prove beneficial to the U1652 case.

Thanks for providing the link to the workshop. I will take a look!

I am currently a Master's student working on the problem of UAV cross view localization and I am focusing on your work in Sample4Geo as a baseline as it is straightforward and easy to implement while providing competitive results.

Any general recommendations or advice would be greatly appreciated! Thanks for taking the time to answer.

**Comment by Skyy93** [comment]
@AthanasiosKwn 

> introducing label noise to the contrastive learning process?

Yes, also in some cases you have drone images that are black because the UAV images are generated through Google Earth, so they are synthetic and in rare cases the rendering of a drone view is within a building. So the Google Earth Rendering Enginge renders the inside of a skyscrapper black and thus the image is also black. This further introduces noise.

> And this phenomenon is amplified when DSS is used because there is a high risk that the hard negatives retrieved are images that contain the anchor point somewhere in the background meaning that these are not true negatives?

Yes.

> If that is the case, then it is interesting to see if DSS coupled with some robust to label noise add-on methodology can also prove beneficial to the U1652 case.

Of course! 

Currently I think adressing label noise is a very interesting direction! You have similar problems in text where hard negative sampling can lead to problems as text often have no clear negatives or sampled examples within a dataset might have the same meaning while being different written. Its of course the same for the Cross-View domain.

Another interesting problem is the more fine-grained prediction as approaches like SliceMatch are currently solving. You would use the retrieval approach to sample near satellite images and then try to predict where in the images the actual location is.

**Comment by AthanasiosKwn** [comment]
@Skyy93 This has been a very informative discussion. I deeply appreciate your time and effort. I will look deeper into the issue of label noise.  On a final note, do you remember any specific examples where the same building was found in two or more building id's. Because I want to visually check it out. Also, is the code used for DSS in U1652 the same that can be found in the cases of the other datasets? If not, is it be possible that you send it to me?

**Comment by Yux1angJi** [comment]
@Skyy93 

> predicting the orientation helps for better performance
> You would use the retrieval approach to sample near satellite images and then try to predict where in the images the actual location is.

Glad to see your interesting discussions. 

Did you consider using image matching as a step in fine-grained prediction? There are many large-scale pre-trained image matching models with good results, such as [GIM](https://github.com/xuelunshen/gim/tree/main). I try to use these models to estimate the homography matrix for cross-view images, which seems to also allow fine-grained prediction. And the zero-shot results are great. On the other hand, image matching and retrieval kind of feel like two tasks that complement each other. Did you consider combining them?

**Comment by Skyy93** [comment]
@AthanasiosKwn I'm sorry, it's been too long, I don't know which ids they are. 

No its not, because you have to be more careful in the sampling if i recall correctly. I can look for the code in the next days, please write me an e-mail, you can find my adress [here](https://skyy93.github.io/).

@Yux1angJi No, I did not so far, but I think this would be a wonderful idea. One problem I could imagine is the different perspective where multiple surfaces are available in one image but not in the other, couldnt this spark some confusion for an image matcher? Or did you test GIM on this problem?

**Comment by Yux1angJi** [comment]
@Skyy93 That’s actually a good point. I haven’t really thought about it since I focus only on UAV cross-view tasks, which usually have some overlapping surfaces. GIM works well for UAV cross-view tasks.
