### ISSUE TITLE
find a mistake in code

### ISSUE THREAD

**Issue by zhicong01** [Skyy93/Sample4Geo#5]
Thanks to the author for the well-commented code. I find a mistake in code.
In the train_university.py (line94-line95)：
`config.query_folder_train = './data/U1652/train/satellite'
config.gallery_folder_train = './data/U1652/train/drone'`
which should change to ：
`config.query_folder_train = './data/U1652/train/drone'
config.gallery_folder_train = './data/U1652/train/satellite'`

**Comment by Skyy93** [comment]
Thanks for your comment, but this is not a mistake, its on purpose. 

Since we train with the InfoNCE loss we have to make sure that the same building is not multiple times in the batch. We do this with our specialized shuffle method in the dataset. The pairs we generate in the dataset __init__ are dependent on the position of the query_folder_train and gallery_folder_train.
