### ISSUE TITLE
GPS smapling

### ISSUE THREAD

**Issue by yejy53** [Skyy93/Sample4Geo#6]
Thank you for your excellent work, but I have some doubts. You mentioned in the ablation section of the paper that CVUSA can also use GPS sampling, but the data set does not seem to provide latitude and longitude.

**Comment by yejy53** [comment]
Secondly, I would like to ask, have your input satellite images undergone polar coordinate conversion? Will there be better results?

**Comment by Skyy93** [comment]
Thank you for the interest in our work. The CVUSA data provides GPS coordinates in the all.csv file. You can get access to the dataset here: https://mvrl.cse.wustl.edu/datasets/cvusa/

We tried and achieved similar results, since the Polar transformation is computational intensive we omitted it for the final paper, because it would further slow down processing. 

If you have further questions please do not hestitate to contact us :) And thanks again for the interest in our work!
